

 build:
  image: zmkfirmware/zmk-build-arm:stable

  cache:
    paths:
      - modules
      - tools
      - zephyr
      - bootloader
      - zmk

  before_script:
    - timestamp=$(date +"%Y%m%d%H%M")
    - echo "file_prefix=$file_prefix"
    - commit=$(echo "${CI_COMMIT_SHA}" | cut -c1-7)
    - branch_name=$(echo "${CI_COMMIT_REF_SLUG}" | awk -F'/' '{print $3}' | cut -c1-4)
    - file_prefix=$timestamp-$commit
    - bin/get_version.sh $branch_name $commit
    - west init -l config
    - west update
    - west zephyr-export

  script:
    - west build -s zmk/app -d build/left -b adv360_left -- -DZMK_CONFIG="${CI_BUILDS_DIR}/config"
    - grep -vE '(^#|^$)' build/left/zephyr/.config
    - west build -s zmk/app -d build/right -b adv360_right -- -DZMK_CONFIG="${CI_BUILDS_DIR}/config"
    - grep -vE '(^#|^$)' build/right/zephyr/.config
    - cp build/left/zephyr/zmk.uf2 ${file_prefix}-left.uf2 && cp build/right/zephyr/zmk.uf2 ${file_prefix}-right.uf2

  artifacts:
    paths:
      - ${file_prefix}-left.uf2
      - ${file_prefix}-right.uf2
